# This action.yml provides a GitHub Action for checking that a Spack recipe
# for a CMake-based package contains variants reflecting the available CMake
# options.
#
# Alex Richert, April 2024
name: 'Spack recipe check'
description: 'Check the Spack recipe for a CMake-based package'

inputs:
  recipe-file:
    required: true
  cmakelists-txt:
    required: true
  ignore-list:
    description: 'Space- or comma-delimited list of CMake option names to ignore because they are not needed in the Spack recipe (e.g., ENABLE_DOCS)'
    default: ''
  alternative-grep:
    description: 'Use a more all-encompassing grep on the Spack recipe'
    default: false

runs:
  using: "composite"
  steps:

    - name: "Checkout package"
      uses: actions/checkout@v4
      with:
        path: package

    - name: "Check Spack recipe"
      shell: bash
      run: |
        ignore_exp="$(echo ${{ inputs.ignore-list }} | sed 's:[\s,]\+:|:g')"
        for opt in $(grep -ioP "^option\(\K[^ ]+" ${{ inputs.cmakelists-txt }} | grep -Ev "$ignore_exp") ; do
          echo -n "Checking for presence of '$opt' CMake option in package.py..."
          if [ ${{ inputs.alternative-grep }} == true ]; then
            found=$(grep -cw "${opt}" ${{ inputs.recipe-file }} || true)
          else
            found=$(grep -cP "define.+\b${opt}\b" ${{ inputs.recipe-file }} || true)
          fi
          if [ $found -eq 0 ]; then
            echo " NOT FOUND"
            count+=1
          else
            echo " found"
          fi
        done
        exit $count
